title: Alejandro Alvarez Perez
baseurl: "/resume/"
exclude:
  - README.md
  - "README_zh-CN.md"
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
  - Rakefile
  - vendor/bundle/ruby/3
    ms/jekyll-3.10.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb