title: Resume — Alejandro Alvarez Perez
repository: aalvarezperez/resume
baseurl: "/resume"
description: "Professional resume and portfolio of Alejandro Alvarez Perez, showcasing experience in software engineering and development."
author: Alejandro Alvarez Perez
url: "https://aalvarezperez.github.io"
lang: "en"

# SEO and Site plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

# Cache settings
headers:
  - scope:
      path: ""
    values:
      cache_control: "no-cache, no-store, must-revalidate"

# Only include what Pages really needs
include:
  - _assets

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - script
  - screenshots
  - fixtures
  - Rakefile
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - node_modules
  # keep any other paths you truly want out of the build

# Service Worker Configuration
service_worker:
  enabled: true
  version: !ruby/object:Time
    epoch: <%= Time.now.to_i %>
