title: Resume — Alejandro Alvarez Perez
repository: aalvarezperez/resume
baseurl: "/resume"

# Only include what Pages really needs
include:
  - _assets

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - script
  - screenshots
  - fixtures
  - Rakefile
  # keep any other paths you truly want out of the build